services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334" # optional gRPC
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data:
